import { chromium } from 'playwright-core';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome', BASE='http://127.0.0.1:8099';
const errs=[],bad=[];
const b=await chromium.launch({executablePath:EXE,args:['--no-sandbox']});
const p=await (await b.newContext({viewport:{width:1400,height:1100}})).newPage();
p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
p.on('response',async r=>{if(r.status()>=500){let t='';try{t=(await r.text()).slice(0,200);}catch{}
  bad.push(`${r.status()} ${r.request().method()} ${r.url().replace(BASE,'')} :: ${t}`);}});
await p.goto(BASE,{waitUntil:'domcontentloaded'});
await p.evaluate(t=>{localStorage.setItem('omerta_token',t);localStorage.setItem('omerta_alltabs','1');
  localStorage.setItem('omerta_welcomed','1');localStorage.setItem('omerta_tour2','1');},process.env.TOK);
await p.goto(BASE,{waitUntil:'networkidle'}); await p.waitForTimeout(2200);
const clean=s=>(s||'').replace(/\s+/g,' ').trim();
const dismiss=async()=>{for(let i=0;i<6;i++){if(!(await p.locator('.modal-bg:not(.hidden)').count()))break;
  await p.evaluate(()=>{const m=document.querySelector('.modal-bg:not(.hidden)');if(m){const bs=m.querySelectorAll('button');if(bs.length)bs[bs.length-1].click();}});await p.waitForTimeout(200);}
  await p.evaluate(()=>{const i=document.querySelector('#introwrap button');if(i)i.click();}).catch(()=>{});};
const go=async t=>{await p.evaluate(tt=>{const el=document.querySelector(`#tabs [data-tab="${tt}"]`);if(el){el.click();return;}
  for(const g of document.querySelectorAll('#grouprail [data-group]')){g.click();
    const e2=document.querySelector(`#tabs [data-tab="${tt}"]`);if(e2){e2.click();return;}}},t);
  await p.waitForTimeout(1100);await dismiss();};
const tap=(text,scope='body')=>p.evaluate(([tx,sc])=>{const root=document.querySelector(sc)||document.body;
  const e=[...root.querySelectorAll('button,a')].filter(x=>{if(x.disabled)return false;
    const r=x.getBoundingClientRect(); if(!r.width||!r.height)return false;
    return (x.innerText||'').trim().toLowerCase().includes(tx.toLowerCase());});
  if(!e.length)return false; e[0].click(); return true;},[text,scope]);
const fill=(sel,v,scope='body')=>p.evaluate(([s,val,sc])=>{const root=document.querySelector(sc)||document.body;
  const el=root.querySelector(s); if(!el)return false; el.value=val; el.dispatchEvent(new Event('input',{bubbles:true})); return true;},[sel,v,scope]);
const toast=async()=>clean(await p.locator('#toast').innerText().catch(()=>'')).slice(0,170);
const act=async(label,fn)=>{ const before=errs.length; await fn(); await p.waitForTimeout(1300); await dismiss();
  console.log(` ${label.padEnd(28)} → ${await toast()}${errs.length>before?'   ⚠️ PAGEERROR':''}`); };
await dismiss();
console.log('=== DOING THINGS ===');
await go('start');
await act('claim the daily streak', ()=>tap('check in','#tab-start'));
await go('streets');
await act('deposit $5,000',       async()=>{ await fill('input','5000','#tab-streets'); await tap('deposit','#tab-streets'); });
await act('travel to Neon Mile',  ()=>tap('The Neon Mile','#tab-streets'));
await act('buy trade goods',      async()=>{ const ok=await p.evaluate(()=>{const s=document.querySelector('#tab-streets select');if(!s)return false;
    const inp=[...document.querySelectorAll('#tab-streets input')].find(i=>i.type==='number'); if(inp){inp.value='3';inp.dispatchEvent(new Event('input',{bubbles:true}));} return true;});
  await tap('buy','#tab-streets'); });
await act('take a corner job',    ()=>tap('take the job','#tab-streets'));
await act('train a stat',         ()=>tap('train','#tab-streets'));
await go('garage');
await act('buy a gun',            ()=>tap('buy','#tab-garage'));
await go('life');
await act('learn a skill',        ()=>tap('learn','#tab-life'));
await go('den');
await act('play the numbers',     async()=>{ await p.evaluate(()=>{for(const i of document.querySelectorAll('#tab-den input[type=number]')){if(!i.value)i.value='100';i.dispatchEvent(new Event('input',{bubbles:true}));}}); await tap('play','#tab-den'); });
await go('pvp');
await act('open the contract board', ()=>Promise.resolve(true));
console.log('\nPAGEERRORS: '+(errs.length?errs.join('\n'):'none'));
console.log('5xx: '+([...new Set(bad)].join('\n')||'none'));
await p.screenshot({path:'/tmp/play/20-actions.png'});
await b.close();
